import LenisProvider from "@/utils/LenisProvider";
import "./globals.css";
import Footer from "@/components/sections/Footer";
import Head from "next/head";
export const metadata = {
  title: "Creating Portfolio",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <body>
        <LenisProvider>
          {children}

          <Footer />
        </LenisProvider>
        {/* {children} */}
      </body>
    </html>
  );
}
